mhartle02/Scriptoria

app.py
templates/home.html

Added app.route('/') function in app.py and VERY basic home.html for link to login page for debugging

Added home.html and associated function in app.py

---

app.py
templates/signup.html

Created basic signup.html outline and accompanying function to handle GET and POST methods

Began signup.html 

---

app.py
templates/login.html

Implemented Session Variables and slightly changed login.html to account for flashed messages, if we decide to implement them instead of autovalidation through flask and html

Greatly modified Login() and slight changes to login.html

---

app.py
initializeDb.py

-Renamed initializeuserdb to initializeDb
-changed db name to Scriptoria

db file rework

---

static/style.css
templates/home.html

Began work on a footer, still learning CSS so its very basic.
Changes to home.html and style.css

Still learning CSS but began work on a footer for the website

---

classes/book.py
libraries/GoogleBooks.py

also moved book class to classes directory

Issue 44: search_books returns list of book objs

---

app.py
classes/book.py
initializeDb.py
templates/home.html

See Title, also further documented in linked issues

Added ReviewDB and BookDB and got BookDb working

---

initializeDb.py

Closes issue #55 by modifying database and adding trigger

Added field in database for average review ratings

---

app.py
classes/book.py
static/style.css
templates/home.html

Currently working to display average reviews for books on home page search but it is pulling from google books API (if we want to change that, its easy)
Expanding on previous pull request from same branch which added average_rating to the database
closes #53

Merging in average_rating display for home screen

---

app.py
static/style.css
templates/home.html
templates/reader.html
templates/review.html

Review function isn't fully working but the issue is contained to only within review.html which has been only my brainchild so far

Review page working partially, pulling with known issues

---

app.py
classes/book.py
initializeDb.py
templates/home.html
templates/reader.html
templates/review.html

Fixed:
- Reader.html displaying results unnecessarily
- Reader.html adding all results on screen to reading list when clicking button
- Reader.html not flashing errors correctly
- Review.html not accepting reviews
- Review.html JavaScript not correctly hiding then displaying review menu
- **Database now stores unique Google_book_id for identifying books when making reviews**
- Database still uses book_id for storing reviews in db to ensure that we only rely on local db for storing our reviews
- some other smaller fixes that i'm probably forgetting

Several big Fixes - See desc. 

---

app.py
initializeDb.py
static/style.css
templates/home.html
templates/my_books.html
templates/profile.html
templates/review.html

Profile works with the exception of profile pictures.
I'm also making this to bookmark my progress before I make some sweeping changes to the way books are queried :P
Closes Issue #43

Added Profile & Began work on changing fetch_book logic

---

app.py
initializeDb.py
templates/review.html

Accidentally missed these in the previous pull request, almost biffed it big time

Additional Changes to profile & mostly fixes to average_rating logic

---

app.py
initializeDb.py
static/style.css
templates/home.html
templates/my_books.html
templates/my_reviews.html
templates/profile.html
templates/review.html

Added page & modified Reviews table, also added link to all headers

Added Reviewed Books Page

---

app.py
initializeDb.py
static/style.css
templates/profile.html

- Friends are added to profile
- an example friendship is autocreated between the two reader accounts
- new database table for userFriends which references userLogins
- added some styling elements to .css but they're subject to change
TBD:
- Allow users to remove friends from profile or visit friend's profile
- Make page for searching for friends

Friends are now displayed on profile.html

---

app.py
static/style.css
templates/home.html
templates/my_books.html
templates/my_reviews.html
templates/profile.html
templates/review.html
templates/search_users.html

Also added link to this page to topnavs for all other pages. Closes issue #86

Addition of search_user.html and associated route

---

app.py
initializeDb.py

initializeDb now hashes the debug user passwords before passing them into the table, signup hashes passwords before storing them in the db, and login checks for password hashes against the user's input and logs in accordingly

Reworking of signup and Werkzeug support

---

app.py
initializeDb.py
templates/profile.html
templates/search_users.html

Friends should be able to be added with pending requests seen from the receiver end but not from the requester's end.
We could add a list of outgoing friend requests also to profile if we want to

Adding pending & accepting friend requests

---

app.py
templates/search_users.html
templates/user_profile.html

Needs more work on public profile design however, but code should fully work

Can now visit user public profiles from the search_users.html page

---

app.py
templates/my_reviews.html

Adds Editing and Updating Reviews functionality to my_reviews.html

---

app.py
initializeDb.py
static/style.css
templates/user_profile.html

Added reviews to user_searched profiles is the biggest addition

Added profile pictures, reviews added to public profiles, and misc. bug fixes
